let monsterAnimainParam = {
    deadDrawScale:{
        isLock:false,
        anValue:0,
        start:0,
        begin:0.01,
        end:1,
        during:40,
    },
    deadDrawGla:{
        isLock:false,
        anValue:0.02,
        start:0,
        begin:0.01,
        end:2,
        during:40,
    },
    deadLineDrawRadius:{
        isLock:false,
        anValue:0,
        start:0,
        begin:1,
        end:80,
        during:40,
    },
    deadLineDrawHeight:{
        isLock:false,
        anValue:0,
        start:0,
        begin:1,
        end:140,
        during:40,
    },
    deadLineDrawGla:{
        isLock:false,
        anValue:0.02,
        start:0,
        begin:0.01,
        end:2,
        during:40,
    },
    flashDrawGla:{
        isLock:false,
        anValue:0.02,
        start:0,
        begin:0.1,
        end:1,
        during:10,
    },
    brokenStoneScale:{
        isLock:false,
        anValue:0.02,
        start:0,
        begin:0.01,
        end:1,
        during:90,
    },
    walk:{
        isLock:false,
        anValue:0,
        start:0,
        begin:1,
        end:100,
        during:100,
    }
}

export default monsterAnimainParam;
